### ISSUE TITLE
HitArea

### ISSUE THREAD

**Issue by dan335** [gluckgames/pixi-packer-parser#2]
To get the hitArea to be correct I did this.

```
sprite.hitArea = new PIXI.Rectangle(
    this.sprite._texture.trim.x,
    this.sprite._texture.trim.y,
    this.sprite._texture.crop.width,
    this.sprite._texture.crop.height
  );
```

What do you think about adding it to pixi-packer-parser?

```
sprite.hitArea = new PIXI.Rectangle(sprite.trim.x, sprite.trim.y, sprite.trim.w, sprite.trim.h);
```

**Comment by marekventur** [comment]
You mean the hitArea of a sprite using a trimmed texture is restricted to the trimmed bit? I have not seen this, but I've also not done any specific testing for that bit. Could you provide a test link of some sort? Otherwise I'll try to reproduce once I find some time.

If it's true the default PIXI texture atlas loader is going to have the same problem and it would probably be best to get a general fix into PIXI instead.

**Comment by dan335** [comment]
I see now it's not something that pixi-packer should do.
